// Autogenerated by Thrift Compiler (0.10.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package main

import (
        "flag"
        "fmt"
        "math"
        "net"
        "net/url"
        "os"
        "strconv"
        "strings"
        "git.apache.org/thrift.git/lib/go/thrift"
        "ongrid2"
)


func Usage() {
  fmt.Fprintln(os.Stderr, "Usage of ", os.Args[0], " [-h host:port] [-u url] [-f[ramed]] function [arg1 [arg2...]]:")
  flag.PrintDefaults()
  fmt.Fprintln(os.Stderr, "\nFunctions:")
  fmt.Fprintln(os.Stderr, "  DataRowSet executeSelectQuery(string authToken, Query query)")
  fmt.Fprintln(os.Stderr, "  void executeNonSelectQuery(string authToken, Query query)")
  fmt.Fprintln(os.Stderr, "  string startBatchExecution(string authToken)")
  fmt.Fprintln(os.Stderr, "  void addQuery(string authToken, string batchID, Query query)")
  fmt.Fprintln(os.Stderr, "  string finishBatchExecution(string authToken, string batchID, Query condition, Query onSuccess)")
  fmt.Fprintln(os.Stderr, "  string batchExecute(string authToken,  queries, Query condition, Query onSuccess)")
  fmt.Fprintln(os.Stderr)
  os.Exit(0)
}

func main() {
  flag.Usage = Usage
  var host string
  var port int
  var protocol string
  var urlString string
  var framed bool
  var useHttp bool
  var parsedUrl url.URL
  var trans thrift.TTransport
  _ = strconv.Atoi
  _ = math.Abs
  flag.Usage = Usage
  flag.StringVar(&host, "h", "localhost", "Specify host and port")
  flag.IntVar(&port, "p", 9090, "Specify port")
  flag.StringVar(&protocol, "P", "binary", "Specify the protocol (binary, compact, simplejson, json)")
  flag.StringVar(&urlString, "u", "", "Specify the url")
  flag.BoolVar(&framed, "framed", false, "Use framed transport")
  flag.BoolVar(&useHttp, "http", false, "Use http")
  flag.Parse()
  
  if len(urlString) > 0 {
    parsedUrl, err := url.Parse(urlString)
    if err != nil {
      fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
      flag.Usage()
    }
    host = parsedUrl.Host
    useHttp = len(parsedUrl.Scheme) <= 0 || parsedUrl.Scheme == "http"
  } else if useHttp {
    _, err := url.Parse(fmt.Sprint("http://", host, ":", port))
    if err != nil {
      fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
      flag.Usage()
    }
  }
  
  cmd := flag.Arg(0)
  var err error
  if useHttp {
    trans, err = thrift.NewTHttpClient(parsedUrl.String())
  } else {
    portStr := fmt.Sprint(port)
    if strings.Contains(host, ":") {
           host, portStr, err = net.SplitHostPort(host)
           if err != nil {
                   fmt.Fprintln(os.Stderr, "error with host:", err)
                   os.Exit(1)
           }
    }
    trans, err = thrift.NewTSocket(net.JoinHostPort(host, portStr))
    if err != nil {
      fmt.Fprintln(os.Stderr, "error resolving address:", err)
      os.Exit(1)
    }
    if framed {
      trans = thrift.NewTFramedTransport(trans)
    }
  }
  if err != nil {
    fmt.Fprintln(os.Stderr, "Error creating transport", err)
    os.Exit(1)
  }
  defer trans.Close()
  var protocolFactory thrift.TProtocolFactory
  switch protocol {
  case "compact":
    protocolFactory = thrift.NewTCompactProtocolFactory()
    break
  case "simplejson":
    protocolFactory = thrift.NewTSimpleJSONProtocolFactory()
    break
  case "json":
    protocolFactory = thrift.NewTJSONProtocolFactory()
    break
  case "binary", "":
    protocolFactory = thrift.NewTBinaryProtocolFactoryDefault()
    break
  default:
    fmt.Fprintln(os.Stderr, "Invalid protocol specified: ", protocol)
    Usage()
    os.Exit(1)
  }
  client := ongrid2.NewDBClientFactory(trans, protocolFactory)
  if err := trans.Open(); err != nil {
    fmt.Fprintln(os.Stderr, "Error opening socket to ", host, ":", port, " ", err)
    os.Exit(1)
  }
  
  switch cmd {
  case "executeSelectQuery":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "ExecuteSelectQuery requires 2 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    arg25 := flag.Arg(2)
    mbTrans26 := thrift.NewTMemoryBufferLen(len(arg25))
    defer mbTrans26.Close()
    _, err27 := mbTrans26.WriteString(arg25)
    if err27 != nil {
      Usage()
      return
    }
    factory28 := thrift.NewTSimpleJSONProtocolFactory()
    jsProt29 := factory28.GetProtocol(mbTrans26)
    argvalue1 := ongrid2.NewQuery()
    err30 := argvalue1.Read(jsProt29)
    if err30 != nil {
      Usage()
      return
    }
    value1 := argvalue1
    fmt.Print(client.ExecuteSelectQuery(value0, value1))
    fmt.Print("\n")
    break
  case "executeNonSelectQuery":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "ExecuteNonSelectQuery requires 2 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    arg32 := flag.Arg(2)
    mbTrans33 := thrift.NewTMemoryBufferLen(len(arg32))
    defer mbTrans33.Close()
    _, err34 := mbTrans33.WriteString(arg32)
    if err34 != nil {
      Usage()
      return
    }
    factory35 := thrift.NewTSimpleJSONProtocolFactory()
    jsProt36 := factory35.GetProtocol(mbTrans33)
    argvalue1 := ongrid2.NewQuery()
    err37 := argvalue1.Read(jsProt36)
    if err37 != nil {
      Usage()
      return
    }
    value1 := argvalue1
    fmt.Print(client.ExecuteNonSelectQuery(value0, value1))
    fmt.Print("\n")
    break
  case "startBatchExecution":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "StartBatchExecution requires 1 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    fmt.Print(client.StartBatchExecution(value0))
    fmt.Print("\n")
    break
  case "addQuery":
    if flag.NArg() - 1 != 3 {
      fmt.Fprintln(os.Stderr, "AddQuery requires 3 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    arg41 := flag.Arg(3)
    mbTrans42 := thrift.NewTMemoryBufferLen(len(arg41))
    defer mbTrans42.Close()
    _, err43 := mbTrans42.WriteString(arg41)
    if err43 != nil {
      Usage()
      return
    }
    factory44 := thrift.NewTSimpleJSONProtocolFactory()
    jsProt45 := factory44.GetProtocol(mbTrans42)
    argvalue2 := ongrid2.NewQuery()
    err46 := argvalue2.Read(jsProt45)
    if err46 != nil {
      Usage()
      return
    }
    value2 := argvalue2
    fmt.Print(client.AddQuery(value0, value1, value2))
    fmt.Print("\n")
    break
  case "finishBatchExecution":
    if flag.NArg() - 1 != 4 {
      fmt.Fprintln(os.Stderr, "FinishBatchExecution requires 4 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    arg49 := flag.Arg(3)
    mbTrans50 := thrift.NewTMemoryBufferLen(len(arg49))
    defer mbTrans50.Close()
    _, err51 := mbTrans50.WriteString(arg49)
    if err51 != nil {
      Usage()
      return
    }
    factory52 := thrift.NewTSimpleJSONProtocolFactory()
    jsProt53 := factory52.GetProtocol(mbTrans50)
    argvalue2 := ongrid2.NewQuery()
    err54 := argvalue2.Read(jsProt53)
    if err54 != nil {
      Usage()
      return
    }
    value2 := argvalue2
    arg55 := flag.Arg(4)
    mbTrans56 := thrift.NewTMemoryBufferLen(len(arg55))
    defer mbTrans56.Close()
    _, err57 := mbTrans56.WriteString(arg55)
    if err57 != nil {
      Usage()
      return
    }
    factory58 := thrift.NewTSimpleJSONProtocolFactory()
    jsProt59 := factory58.GetProtocol(mbTrans56)
    argvalue3 := ongrid2.NewQuery()
    err60 := argvalue3.Read(jsProt59)
    if err60 != nil {
      Usage()
      return
    }
    value3 := argvalue3
    fmt.Print(client.FinishBatchExecution(value0, value1, value2, value3))
    fmt.Print("\n")
    break
  case "batchExecute":
    if flag.NArg() - 1 != 4 {
      fmt.Fprintln(os.Stderr, "BatchExecute requires 4 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    arg62 := flag.Arg(2)
    mbTrans63 := thrift.NewTMemoryBufferLen(len(arg62))
    defer mbTrans63.Close()
    _, err64 := mbTrans63.WriteString(arg62)
    if err64 != nil { 
      Usage()
      return
    }
    factory65 := thrift.NewTSimpleJSONProtocolFactory()
    jsProt66 := factory65.GetProtocol(mbTrans63)
    containerStruct1 := ongrid2.NewDBBatchExecuteArgs()
    err67 := containerStruct1.ReadField2(jsProt66)
    if err67 != nil {
      Usage()
      return
    }
    argvalue1 := containerStruct1.Queries
    value1 := argvalue1
    arg68 := flag.Arg(3)
    mbTrans69 := thrift.NewTMemoryBufferLen(len(arg68))
    defer mbTrans69.Close()
    _, err70 := mbTrans69.WriteString(arg68)
    if err70 != nil {
      Usage()
      return
    }
    factory71 := thrift.NewTSimpleJSONProtocolFactory()
    jsProt72 := factory71.GetProtocol(mbTrans69)
    argvalue2 := ongrid2.NewQuery()
    err73 := argvalue2.Read(jsProt72)
    if err73 != nil {
      Usage()
      return
    }
    value2 := argvalue2
    arg74 := flag.Arg(4)
    mbTrans75 := thrift.NewTMemoryBufferLen(len(arg74))
    defer mbTrans75.Close()
    _, err76 := mbTrans75.WriteString(arg74)
    if err76 != nil {
      Usage()
      return
    }
    factory77 := thrift.NewTSimpleJSONProtocolFactory()
    jsProt78 := factory77.GetProtocol(mbTrans75)
    argvalue3 := ongrid2.NewQuery()
    err79 := argvalue3.Read(jsProt78)
    if err79 != nil {
      Usage()
      return
    }
    value3 := argvalue3
    fmt.Print(client.BatchExecute(value0, value1, value2, value3))
    fmt.Print("\n")
    break
  case "":
    Usage()
    break
  default:
    fmt.Fprintln(os.Stderr, "Invalid function ", cmd)
  }
}
